blank_issues_enabled: true
contact_links:
  - name: Official Resonite Discord
    url: https://discord.gg/resonite
    about: The place to discuss all things Resonite
  - name: Moduprint Discussion on Discord
    url: https://discord.com/channels/1040316820650991766/1366552923118633092
    about: Moduprint discussion channel
